# Generated by Django 3.1.7 on 2021-03-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_auto_20210330_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureauthor',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pictureauthor',
            name='link_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
