# Generated by Django 3.1.7 on 2021-03-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grape',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ('name',)},
        ),
    ]
