# Generated by Django 3.1.7 on 2021-03-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_auto_20210324_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='grapes',
            field=models.ManyToManyField(to='wine.Grape'),
        ),
    ]
