# Generated by Django 3.1.7 on 2021-03-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_wine_grapes'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/wines/'),
        ),
    ]
