# Generated by Django 3.1.7 on 2021-03-29 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0007_auto_20210329_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
