# Generated by Django 3.1.7 on 2021-03-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0008_auto_20210329_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
