# Generated by Django 3.1.7 on 2021-03-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_auto_20210330_1101'),
        ('wine', '0009_auto_20210329_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='wine',
            name='type',
        ),
        migrations.AddField(
            model_name='grape',
            name='img_author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producer.pictureauthor'),
        ),
        migrations.AddField(
            model_name='wine',
            name='img_author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producer.pictureauthor'),
        ),
        migrations.AddField(
            model_name='wine',
            name='price',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('economic', 'Economic'), ('reasonable', 'Reasonable'), ('expensive', 'Expensive')], default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='wine',
            name='trending_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='types',
            field=models.ManyToManyField(blank=True, to='wine.Tag'),
        ),
    ]
