# Generated by Django 3.1.7 on 2021-03-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_auto_20210330_1252'),
        ('wine', '0010_auto_20210330_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grape',
            name='img_author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producer.pictureauthor'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='img_author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producer.pictureauthor'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='trending_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
