# Generated by Django 3.1.7 on 2021-03-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0012_auto_20210330_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='trending_rank',
        ),
        migrations.AddField(
            model_name='wine',
            name='pageviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='wines', to='wine.Tag'),
        ),
    ]
